version: '3'

services:
  latest:
    image: wernight/duplicity:latest
    build:
      context: latest
  stable:
    image: wernight/duplicity:stable
    build:
      context: stable
  python2:
    image: wernight/duplicity:python2
    build:
      context: python2
